import React from "react";
import {
  Activity,
  BadgeDollarSign,
  BarChart3,
  Bell,
  Bot,
  ChevronDown,
  ChevronRight,
  Boxes,
  BriefcaseBusiness,
  Building2,
  Cable,
  ClipboardList,
  CircleHelp,
  Code2,
  CreditCard,
  Database,
  FileSpreadsheet,
  FileText,
  Folder,
  GitBranch,
  BookOpen,
  Gauge,
  HandCoins,
  Headphones,
  Image,
  Home,
  Layers3,
  LifeBuoy,
  ListChecks,
  Mic,
  Minimize2,
  Network,
  PackageCheck,
  Paperclip,
  Percent,
  PhoneCall,
  ReceiptText,
  RadioTower,
  Search,
  Send,
  ServerCog,
  Settings2,
  ShoppingCart,
  SlidersHorizontal,
  Sparkles,
  TicketCheck,
  Truck,
  UserRoundSearch,
  UsersRound,
  Menu,
  X,
  Workflow
} from "lucide-react";

const icons = {
  activity: Activity,
  bell: Bell,
  billing: CreditCard,
  bot: Bot,
  coefficients: SlidersHorizontal,
  code: Code2,
  customers: UsersRound,
  customerSearch: UserRoundSearch,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  dashboard: Home,
  database: Database,
  export: FileSpreadsheet,
  file: FileText,
  folder: Folder,
  finance: HandCoins,
  github: GitBranch,
  image: Image,
  knowledge: BookOpen,
  leads: Send,
  mic: Mic,
  minimize: Minimize2,
  network: Network,
  menu: Menu,
  orders: ClipboardList,
  paperclip: Paperclip,
  opportunities: BriefcaseBusiness,
  pricing: BadgeDollarSign,
  products: Boxes,
  provisioning: Truck,
  reports: BarChart3,
  radio: RadioTower,
  search: Search,
  server: ServerCog,
  service: LifeBuoy,
  serviceDesk: Headphones,
  settlement: ReceiptText,
  settings: Settings2,
  sla: Gauge,
  sales: ShoppingCart,
  sparkles: Sparkles,
  strategic: Sparkles,
  tickets: TicketCheck,
  workflow: Workflow,
  account: Building2,
  cable: Cable,
  help: CircleHelp,
  layers: Layers3,
  package: PackageCheck,
  percent: Percent,
  checks: ListChecks,
  phone: PhoneCall,
  close: X
};

export function Icon({ name, className = "nav-icon", size }) {
  const Component = icons[name] || Home;
  return <Component className={className} size={size} aria-hidden="true" strokeWidth={2} />;
}
