import React from "react";
import {
  Activity,
  BadgeDollarSign,
  BarChart3,
  Bell,
  Boxes,
  BriefcaseBusiness,
  Building2,
  Cable,
  ClipboardList,
  CreditCard,
  FileSpreadsheet,
  Gauge,
  HandCoins,
  Headphones,
  Home,
  Layers3,
  LifeBuoy,
  ListChecks,
  Network,
  PackageCheck,
  Percent,
  PhoneCall,
  ReceiptText,
  Search,
  Send,
  Settings2,
  ShoppingCart,
  SlidersHorizontal,
  Sparkles,
  TicketCheck,
  Truck,
  UserRoundSearch,
  UsersRound,
  Workflow
} from "lucide-react";

const icons = {
  activity: Activity,
  bell: Bell,
  billing: CreditCard,
  coefficients: SlidersHorizontal,
  customers: UsersRound,
  customerSearch: UserRoundSearch,
  dashboard: Home,
  export: FileSpreadsheet,
  finance: HandCoins,
  leads: Send,
  network: Network,
  orders: ClipboardList,
  opportunities: BriefcaseBusiness,
  pricing: BadgeDollarSign,
  products: Boxes,
  provisioning: Truck,
  reports: BarChart3,
  search: Search,
  service: LifeBuoy,
  serviceDesk: Headphones,
  settlement: ReceiptText,
  settings: Settings2,
  sla: Gauge,
  sales: ShoppingCart,
  strategic: Sparkles,
  tickets: TicketCheck,
  workflow: Workflow,
  account: Building2,
  cable: Cable,
  layers: Layers3,
  package: PackageCheck,
  percent: Percent,
  checks: ListChecks,
  phone: PhoneCall
};

export function Icon({ name, className = "nav-icon", size }) {
  const Component = icons[name] || Home;
  return <Component className={className} size={size} aria-hidden="true" strokeWidth={2} />;
}
